name: Rust

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build Debug
      run: cargo build --verbose

    - name: Build Release
      run: cargo build --release --verbose

    - name: Run tests
      run: cargo test --verbose

    - name: Upload Debug Artifact
      uses: actions/upload-artifact@v3
      with:
        name: debug-build
        path: |
          target/debug/**/*
        if-no-files-found: error

    - name: Upload Release Artifact
      uses: actions/upload-artifact@v3
      with:
        name: release-build
        path: |
          target/release/**/*
        if-no-files-found: error

